version: '3'
services:
  weather_app:
    build: .
    container_name: weather_app
    restart: always
    depends_on:
      - db
    environment:
      - API_KEY=${API_KEY}
    ports:
      - "5000:5000"
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
